version: '3'

services:
    juridico-db:
        build: .docker/database/
        container_name: juridico-db
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    juridico-node:
        build: .
        container_name: juridico-node
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            - juridico-db
        volumes:
            - .:/usr/juridico-node
        command: npm run dev
volumes:
    postgres_data: